### ISSUE TITLE
[BUG] Getting build error '../Downloads/azure-notificationhubs-xamarin-main/src/bindings/output' doesn't exist.

### ISSUE THREAD

**Issue by smobiledev** [Azure/azure-notificationhubs-xamarin#50] opened 2021-02-02 11:52 UTC
After downloading the latest source code and whenever am trying to run the solution getting error.

**Comment by marstr** [comment] 2021-02-03 17:30
Closting as duplicate of #38

**Closed by marstr** 2021-02-03 17:30 UTC
