### ISSUE TITLE
[BUG]NotificationMessageReceived does not trigger when opening notification from tray

### ISSUE THREAD

**Issue by MyotisX** [Azure/azure-notificationhubs-xamarin#40] opened 2020-12-15 15:18 UTC
**Describe the bug**
NotificationMessageReceived  does not trigger when a notification is clicked from the notification tray (background notification). It does trigger when the notification is received in foreground.

***Exception or Stack Trace***
[removed]

**To Reproduce**
Implemented Azure Notification Hubs for Xamarin (azure-notificationhubs-xamarin). Sent notification from Azure Notification "Test Send" on android simulator with app in background. Payload : 
`{
	"notification":{
		"title":"Notification Hub Test Notification",
		"body":"This is a sample notification delivered by Azure Notification Hubs."
	},
	"data":{
		"property1":"value1",
		"property2":42
	}
}
`

***Code Snippet***
`// Add an event handler
NotificationHub.NotificationMessageReceived += OnNotificationMessageReceived;

// The handler
private void OnNotificationMessageReceived(object sender, NotificationMessageReceivedEventArgs e)
{
    // Do something with the message
    Console.WriteLine($"Title: {e.Title}");
    Console.WriteLine($"Body: {e.Body}");
}`

**Expected behavior**
Event must trigger when a background notification is clicked. Like it did in app center with 
`Push.PushNotificationReceived`

**Setup (please complete the following information):**
 - OS: Android 9.0
 - IDE : Visual Studio 2019 Community 16.8.2
 - main branch of azure-notificationhubs-xamarin

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by MyotisX** [comment] 2020-12-15 21:25
Additional information:

the problem occurs when I'm sending a Notification+data payload. The notification appears in the system's tray. When pressed, the app opens and the MainActivity receives the data in it's intent's extras. However, the NotificationListener does not trigger OnPushNotificationReceived. This used to work with AppCenter.

@marstr could you help with this? I am migrating from AppCenter and time is running out.

**Comment by marstr** [comment] 2020-12-16 22:10
Howdy! I'm here to help.

You are correct - the Android SDK doesn't support this the way ACP does. While there's a lot more I could say, the basic thinking is that most of the time the two ingress points represent pretty darn different scenarios. My recommendation is to build a class of your own that knows how to extract the information it needs out of either the event arguments that are delivered to you via Notification Hubs, or by extracting the data out of an `Intent` delivered to you by the Android system.

**Comment by marstr** [comment] 2021-01-14 21:10
Closing this out as it is by design, the expected implementation has been described, and there haven't been any follow-up questions in the last month.

**Closed by marstr** 2021-01-14 21:10 UTC
